### ISSUE TITLE
General Sander command line support

### ISSUE THREAD

**Issue by GregorySchwing** [bioexcel/biobb_amber#9]
**Is your feature request related to a problem? The sander class is incomplete, only offering a handful of the command line arguments available, and there is no way for the user to define custom command line arguments.

For instance, I am trying to use sander to run a 3DRISM calculation, and a command line argument I need is -xvv and -guv.  There is no way for me to do this currently. 

The feature request is to allow the user to pass a dict of command flags and their optional argument to be appended to the end of the self.cmd string

**Comment by adamhospital** [comment]
Hi Gregory,

all BioBB blocks have a "dev" property, only for development purposes (that's why it is not documented). See the source code [here](https://github.com/bioexcel/biobb_common/blob/492f9aa8683961938af5c47700d7804911c337c1/biobb_common/generic/biobb_object.py#L230).

This property lets you add additional command flags. 

Hope this helps.
